export const SITE = {
  site: {
    url: "https://vietdoo.vndo.vn",
    title: "Do Quoc Viet (vietdoo) — Software Engineer @ VNPT | Founder @ VNDO",
    description:
      "Official portfolio of Do Quoc Viet (vietdoo), Software Engineer @ VNPT & Founder @ VNDO. Specializing in Big Data engineering, distributed systems, high-performance backend, cloud-native microservices, and AI agent architecture.",
    locale: "en_US",
    alternateLocales: ["vi_VN"],
  },
  author: {
    firstName: "Do Quoc",
    lastName: "Viet",
    fullName: "Do Quoc Viet",
    fullNameVi: "Do Quoc Viet",
    shortName: "vietdoo",
    alternateNames: [
      "Đỗ Quốc Việt",
      "Do Quoc Viet",
      "vietdoo",
      "Đỗ Quốc Việt VNPT",
      "Do Quoc Viet VNPT",
      "Do Quoc Viet (vietdoo)",
      "vietdoo software engineer",
      "vietdoo-folio",
      "Quoc Viet Do",
    ],
    jobTitle: "Software Engineer",
    jobTitleFull: "Software Engineer @ VNPT | Founder @ VNDO",
    yearsOfExperience: "3+",
    company: "VNPT",
    companyVi: "VNPT",
    companyEn: "VNPT Group",
    companyAliases: [
      "VNPT Group",
      "VNPT",
    ],
    project: "Vietnam National Public Service Portal",
    projectVi: "Cổng Dịch vụ công Quốc gia",
    projectAliases: [
      "Vietnam National Public Service Portal",
      "Cổng Dịch vụ công Quốc gia",
      "National Public Service Portal",
    ],
    domains: [
      "Big Data Engineering",
      "Distributed Systems",
      "Backend Engineering",
      "AI Engineering",
      "Cloud Native",
      "Microservices",
      "Streaming Architecture",
    ],
    coreTechnologies: [
      "Apache Spark",
      "Apache Kafka",
      "Hadoop HDFS",
      "Python",
      "C++",
      "Spring Boot",
      "FastAPI",
      "Redis",
      "PostgreSQL",
      "Docker",
      "Kubernetes",
      "Linux",
      "TypeScript",
      "Next.js",
      "AI Agent Architecture",
    ],
    twitterHandle: "vietdoo", // without "@"
    keywords: [
      "Đỗ Quốc Việt",
      "Do Quoc Viet",
      "vietdoo",
      "Đỗ Quốc Việt VNPT",
      "Do Quoc Viet VNPT",
      "Do Quoc Viet (vietdoo)",
      "vietdoo software engineer",
      "vietdoo portfolio",
      "vietdoo-folio",
      "Software Engineer",
      "Software Engineer VNPT",
      "VNPT Group",
      "Tập đoàn Bưu chính Viễn thông Việt Nam",
      "Vietnam Posts and Telecommunications Group",
      "Cổng Dịch vụ công Quốc gia",
      "Vietnam National Public Service Portal",
      "Big Data Engineering",
      "Big Data Engineer Vietnam",
      "Distributed Systems",
      "Backend Engineering",
      "AI Engineering",
      "Cloud Native",
      "Microservices",
      "Streaming Architecture",
      "Apache Spark",
      "Apache Kafka",
      "Hadoop HDFS",
      "Data Pipelines",
      "Python",
      "C++",
      "Spring Boot",
      "FastAPI",
      "Cloud-Native Microservices",
      "Redis",
      "PostgreSQL",
      "SQL",
      "NoSQL",
      "SQL / NoSQL",
      "Kubernetes",
      "Docker",
      "Linux",
      "TypeScript",
      "Next.js",
      "AI Agent Architecture",
      "Handover Architecture",
    ],
  },
  location: {
    locality: "Ho Chi Minh City",
    countryName: "Vietnam",
    countryCode: "VN",
    timezone: "Asia/Ho_Chi_Minh",
  },
  links: {
    github: "https://github.com/vietdoo",
    linkedin: "https://www.linkedin.com/in/vietdoo/",
    twitter: "https://x.com/vietdoo",
    medium: "https://vndo.vn",
    dribbble: "https://vndo.vn",
    email: "vietdoo@outlook.com",
    goodreads: "https://www.goodreads.com/user/show/165632513",
  },
  cal: {
    username: "vietdoo",
    durationNamespace: "15min",
    origin: "https://cal.com",
  },
  visitedCountries: ["Vietnam"],
  visitedProvinces: [
    "Ha Noi",
    "Ho Chi Minh",
    "Da Nang",
    "Hai Phong",
    "Lam Dong",
    "Dong Nai",
    "Tay Ninh",
    "Khanh Hoa",
    "Thanh Hoa",
    "Ninh Binh",
  ],
};

